### ISSUE TITLE
Rooms with 200+ people will error on the count display

### ISSUE THREAD

**Issue by xklob** [vartan/robin-grow#10]
After you reach 200 people, the sidebar stops showing all of them and says "..and [x] more". This causes issues with the counting of votes.

however you can probably use the /count and /tally commands to fix this.

**Comment by PeachIceTea** [comment]
Will be working on that :)

**Comment by vartan** [comment]
Good point, I'm currently updating this between coding at work, so I don't have the time to deal with this right now. 

I wouldn't use the commands because it's a bit invasive to replace peoples textboxes while they might be typing. Is there another way to get this information using an API?

**Comment by xklob** [comment]
No idea about an API, but couldn't you send the commands without actually typing them in the box via js?

**Comment by PeachIceTea** [comment]
The form post to /api/robin/{random string}/message

**Comment by xklob** [comment]
The string must be a hash of something. It's constant across all my message requests.

**Comment by PeachIceTea** [comment]
Its the room id

**Comment by vartan** [comment]
Any clue how to get the room id? I find it in the code as 

e.config.robin_room_id

Does it appear anywhere in the DOM?

**Comment by vartan** [comment]
It is in the setup!

**Comment by vinnymac** [comment]
Yes, it is in the form action.

``` javascript
$("#robinSendMessage")[0].getAttribute('action').split('/')[3]
```

**Comment by vartan** [comment]
I don't think commands actually go through the API, they are handled in the javascript file

**Comment by xklob** [comment]
I also suggest that we get a status box that will show what the next action will be. EG havit show next action: GROW if enough people say grow, etc. This is relevant to this issue because we'll be using the same commands.

**Comment by PeachIceTea** [comment]
`chatCommands: {
            commands: function() {
                this.addSystemMessage("/vote abandon - vote to abandon"),
                this.addSystemMessage("/vote stay - vote to stay"),
                this.addSystemMessage("/vote grow - vote to grow"),
                this.addSystemMessage("/whois <user_in_room> - provide information about <user_in_room>")
            },`
Yep. The commands are handled by the script.

**Comment by vartan** [comment]
I believe we might be able to load the robin page to get peoples' statuses, there is a list of users embedded there

**Comment by vinnymac** [comment]
Just tested posting via JS, and it looks like you need to set the `x-modhash` header otherwise you get a `403 Forbidden`.

**Comment by vartan** [comment]
``` javascript
$.get("/robin/",function(a){
    var start = "{"+a.substring(a.indexOf("\"robin_user_list\": ["));
    var end = start.substring(0,start.indexOf("}]")+2)+"}";
    console.log(end);
    console.log(JSON.parse(end));
});
```

**Comment by PeachIceTea** [comment]
Works for me. So we parse that?

**Comment by vartan** [comment]
Yeah this will work. i get 808 users

``` javascript
var list = {}
$.get("/robin/",function(a){
    var start = "{"+a.substring(a.indexOf("\"robin_user_list\": ["));
    var end = start.substring(0,start.indexOf("}]")+2)+"}";
    console.log(end);
    console.log();
    list = JSON.parse(end).robin_user_list;
});
```

**Comment by vartan** [comment]
```
list.filter(function(voter){return voter.vote === "INCREASE"}).length
```

**Comment by curioussavage** [comment]
haha nice! I was going to suggest scraping that config script tag we put in there. thats what my chrome extension was doing

**Comment by curioussavage** [comment]
I think a black-list for users and autoremoval of their posts would be sweet, was going to add it to my extension but there are already too many scripts

**Comment by xklob** [comment]
At this point a chrome extension might be better.

**Comment by vartan** [comment]
It's very fragile if usernames contain the characters we're looking for so that will have to be fixed.

But what do you think of this in update, and increasing update time to each 30 seconds

``` javascript

        var list = {}
        $.get("/robin/",function(a){
            var start = "{"+a.substring(a.indexOf("\"robin_user_list\": ["));
            var end = start.substring(0,start.indexOf("}]")+2)+"}";
            console.log(end);
            console.log();
            list = JSON.parse(end).robin_user_list;
            var increaseCount = list.filter(function(voter){return voter.vote === "INCREASE"}).length;
            var abandonCount = list.filter(function(voter){return voter.vote === "ABANDON"}).length;
            var novoteCount = list.filter(function(voter){return voter.vote === "NOVOTE"}).length;
            var continueCount = list.filter(function(voter){return voter.vote === "CONTINUE"}).length;
            $('#robinVoteWidget .robin--vote-class--increase .robin-chat--vote-label').html('grow<br>('+increaseCount+')');
            $('#robinVoteWidget .robin--vote-class--abandon .robin-chat--vote-label').html('abandon<br>('+abandonCount+')');
            $('#robinVoteWidget .robin--vote-class--novote .robin-chat--vote-label').html('no vote<br>('+novoteCount+')');
            $('#robinVoteWidget .robin--vote-class--continue .robin-chat--vote-label').html('stay<br>('+continueCount+')');

        });
```

**Comment by xklob** [comment]
30 seconds is too high. I'd prefer 5 seconds.

**Comment by vartan** [comment]
I made it 10 seconds. This is now in the current version
