### ISSUE TITLE
Settings button on safari not working after room grows too big?

### ISSUE THREAD

**Issue by shokk** [vartan/robin-grow#108]
I was not able to press the Settings button anymore after the room grew last 200 users. Is there a key shortcut we can use?

**Comment by vartan** [comment]
What happens?

**Comment by shokk** [comment]
Sorry for the vague description. It is just not clickable. Neither are the Stay or Grow buttons. I had to switch to Chrome for it to work again.

**Comment by vartan** [comment]
Can you disable the userscript and check if these work? I think I experience the same thing as you on Safari, but it's even if the userscript is disabled.

**Comment by vartan** [comment]
![image](http://i.imgur.com/7apUBtZ.png)

**Comment by shokk** [comment]
Yes it looks like that for me with the script. 
I can however click the Stay-Grow buttons while the script is not enabled.

**Comment by vartan** [comment]
Fixed
