### ISSUE TITLE
Multiple channels?

### ISSUE THREAD

**Issue by joeymavity** [vartan/robin-grow#111]
Could you make it so you can join multiple channels? I'd like to be in trivia and general chat. Looks like it'd take some work (need an array of channels delimited by, I assume, the comma - and then also to let the user switch how the input string begins), but it'd be appreciated.

**Comment by dashed** [comment]
~~There's a commit on this but remains unfinished/unpolished: https://github.com/vartan/robin-grow/commit/64c7b5593e384cff85e5e5fad48b534a87141cd6~~

**Comment by dashed** [comment]
for the T16 room, this was necessary and, some folks and I worked on getting decent multichat support: https://github.com/5a1t/robin-grow

**Comment by vartan** [comment]
I'd also like to see this feature in the main branch.
