### ISSUE TITLE
Change vote to stay when room is 4000 big

### ISSUE THREAD

**Issue by jer-lim** [vartan/robin-grow#114]
Hello friends, we at https://github.com/keythkatz/Robin-Autovoter/ have changed the code to auto-stay by default at 4000, and it'll be great if your larger userbase could do that too.

**Comment by tambry** [comment]
What's the reason?

**Comment by jer-lim** [comment]
because

1- The chances of merging 2x 4000 is very unlikely
2- Who's going to get a higher stay count than 4000? That's a whole active subreddit.
3- Even if the 2 highest merge now, it will still not hit 4000, so it's a long way away.

**Comment by frias0** [comment]
However, the joke won't end until the 8th

**Comment by matchai** [comment]
Alternatively, the script could switch to "Stay" if the majority isn't already set to "Grow", during the last 10 seconds before a change.
That could potentially save a room, without dismissing the possibility to grow.

**Comment by Bottswana** [comment]
Not sure this is our call to make.

**Comment by tambry** [comment]
I think matchai's proposal makes sense. It would at least save a portion of the rooms.

**Comment by matchai** [comment]
It could be a togglable setting or a prompt saying something like "The room is about to be disbanded. Would you like to change your vote?"

**Comment by jer-lim** [comment]
Will it stay on tier 17?

**Comment by vartan** [comment]
No, but you're a human being that can press stay once you hit t17

**Comment by dkisselev** [comment]
Staying right at the start of T17 is not smart!

We need to get past the reaping, which means that either one of Stay/Grow need to beat out Abandon/No Vote.

Many people aren't going to get the "Stay at 17" memo, so stay/grow will be a split vote, and there's a higher likelyhood of failure. We need to get past the reaping, _then_ go for stay (if that's what the users wish to do... I don't personally agree with auto-stay being pushed out as an automatic update onto people).
