### ISSUE TITLE
Save the mutes/allow unmuting

### ISSUE THREAD

**Issue by tambry** [vartan/robin-grow#117]
There are multiple bots and saving the mutes would be useful. Though a unmute option would be needed.

There are also multiple "John Madden" bots and a "r/longevity" bot spamming such messages. Would be useful to have them added to the filters.

**Comment by dashed** [comment]
This isn't currently saved yet. It's saved onto a variable whose state is lost when refreshing the page.

There needs to be a decent mute management before this is possible.

**Comment by tambry** [comment]
Yeah, that makes. For the record, here are some examples from the JohnMadden bots' messages:

> Hello. I am John Madden. A human participant could not be found.
> John Madden could find a room!
> John Madden does not sleep.
> John Madden is a human!
> John Madden thinks _username_ has a potty mouth!
> [Madden Facts] _random fact here_

And some more for some other bot:

> I had a bad dream last night. No more bad dreams. plz stay. https://redd.it/4d3vuy

**Comment by voltaek** [comment]
Feature is complete, closing.
