### ISSUE TITLE
3rd Party Statistics

### ISSUE THREAD

**Issue by Chr12t0pher** [vartan/robin-grow#118]
What would your/the general opinion be on using robin-grow to send some general datapoints (room name, size of room, participants) to a back-end in order to find out the largest room, let people search for where other people are/have come from, etc.

I'd be willing to make the back-end, just need to know if people would be happy to see it implemented into robin-grow (because of it's large userbase).

Opt-in could be a good idea (likely to be a decent number of people who [understandably] don't want to send data to a random server).

**Comment by Chr12t0pher** [comment]
I propose a POST with the following data:

```
{
  "room_id": "ec358f84-f97f-11e5-97de-0e31fc1b0d95",
  "room_name": "OlhrGNanhemeinomnilyrs",
  "room_date": "1459677384000",
  "room_user_list": ["user1", "user2", "etc"]
}
```

`room_user_list` could also possibly include the voting intention and data should be sent once at room creation, and again just before the polls close - in order to record anyone who may have `/leave_room`'d.

**Comment by dashed** [comment]
Unfortunately, I'm against this.

**Comment by devoidfury** [comment]
I like the idea, but for privacy concerns for the end-users, I'd prefer not to add more outbound connections.

**Comment by l3d00m** [comment]
Make it opt-in maybe? It would make it easier for the leaderboard.

**Comment by Bottswana** [comment]
Now this is merged: https://github.com/vartan/robin-grow/pull/133
Is this not relatively redundant?

**Comment by Chr12t0pher** [comment]
Sounds alright to me - closing.
