### ISSUE TITLE
The spam protection removes robin messages

### ISSUE THREAD

**Issue by xklob** [vartan/robin-grow#13]
Messages from robin start with [, so they don't show up,

**Comment by PeachIceTea** [comment]
Its a weird idea anyway. If we want to add chat enhancements we should give the user the ability to mute someone.

**Comment by PeachIceTea** [comment]
So just tested it. The newest version doesn't remove [robin] messages.

**Comment by Qjammer** [comment]
You should consider closing this issue

**Comment by vartan** [comment]
Agreed, re-open the issue if you can find a more specific example. I can't recreate this.

**Comment by vartan** [comment]
Found a place where this is happening, fixed now in commit f691fab7fe9caefdcb25d1d1e793e05af5bb3471

**Comment by devoidfury** [comment]
This is fixed in recent versions.
