### ISSUE TITLE
Linkify http:// URLs

### ISSUE THREAD

**Issue by KronK0321** [vartan/robin-grow#132]
Would it be possible to have URLs parsed and turned into hyperlinks that open in a new window?

Many times, imgur links and reddit threads are posted in chat. Copy/pasting the URL is sometimes tricky due to the fast-moving chat.

I understand the potential for abuse but maybe the feature could be opt-in in the settings?

**Comment by tetra-fox** [comment]
already added in de2d5e8

**Comment by KronK0321** [comment]
Hm, I had a look at the code and it seems like only https:// and ftp:// URLs are linkified. I just tested in chat and http:// is not

Is this a bug or intended?

**Comment by Brayzure** [comment]
I just tested and it appears that http:// is linkified, though not always. The regex for detecting a url supports it.

**Comment by dashed** [comment]
@Brayzure only linkifies the first occurrence
