### ISSUE TITLE
AutoVote only working client-side?

### ISSUE THREAD

**Issue by ieatyou1** [vartan/robin-grow#138]
So when we merge with a new room, it automatically votes grow for me, the grow button's highlighted and when I do /vote grow it says that is already your vote. However, when I ask other people whether that's my vote, they say no and when the time comes for the next merge, I get kicked out. I have to manually change my vote to stay and then back to grow again. I'm on Google Chrome, using TaperMonkey. I'm on Windows 10.

**Comment by vartan** [comment]
That's disappointingly bad implementation on reddit's end, I think we are probably clicking 'grow' too quickly then
