### ISSUE TITLE
Mute presets

### ISSUE THREAD

**Issue by dashed** [vartan/robin-grow#139]
We need a built-in list of users to auto-mute.

**Comment by vartan** [comment]
I'm not sure if I agree with a built-in list of users to auto mute. We need muting saved between refreshes though, if someone hasn't added that in yet.

**Comment by dashed** [comment]
@vartan Well I meant there are obviously bots in the chat that are intentionally spammy. Users shouldn't need to maintain a new list on every merge. 

The problem is that the chat moves too fast to click on the names of the spamming bots.

---

Users should still be able to amend on top of the preset.

**Comment by dashed** [comment]
I've observed this in T15 and T16.

**Comment by dkisselev** [comment]
If you scroll up, the chat stops autoscrolling.

But yeah, saving the spamlist is still necessary.

**Comment by dashed** [comment]
@dkisselev The autoscrolling stop actually doesn't really work when "Max messages before pruning" is reached.

**Comment by vartan** [comment]
If #140 works, then this is resolved.
