### ISSUE TITLE
Problems sending messages and using slash commands with channel filters enabled

### ISSUE THREAD

**Issue by nandhp** [vartan/robin-grow#152]
I set up channel filters and checked the box for "filter by channel". I observe the following:
1. Slash commands don't work with any channel selection (they get the channel prefix prepended to the message and are sent to the chat).
2. When I select the "all" channel, I get a channel prefix added to each of my messages anyway. (One of the leftmost characters in the filter string.) So I cannot use any slash command in "all" either.
3. If I turn off the "filter by channel" checkbox, switching between channel tabs still seems to work, and I can even send messages on other other channels. Further, now sending messages on the "all" channel now works as expected, and I can even use slash commands. However, slash commands still don't work on any other channel.

I tested this with both Firefox+Greasemonkey and with Chrome+Tampermonkey. I am using Grow 2.0.5.

**Comment by vartan** [comment]
With filter by channel, you are forced to use a channel so the all tab will use your first channel as a default. 

I tested /me on 2.0.5 and it works just fine. Do you have another userscript?

**Comment by nandhp** [comment]
The problem does not seem to occur with `/me` -- that seems to be the only command that works.

The commands I cannot use are `/commands`, `/count`, `/tally`, `/whois`, and so on.

**Comment by vartan** [comment]
Oh that makes sense. you have it right. I'll fix it tomorrow
