### ISSUE TITLE
Send more than 140 characters.

### ISSUE THREAD

**Issue by ghost** [vartan/robin-grow#155]
I think that can be done by automatically sending the messages in 140 character chunks.

Since it's sent by javascript and not physically pressing the "enter" key, it should be much faster.

**Comment by tetra-fox** [comment]
I think the character count is checked client side and server side. Your browser checks if the maxlength is ≤ to 140 (or a different value if you change it in DevTools) and then when that check passes, the server gets the message and checks if your message's character count is ≤ 140 and fails if it is over 140 characters. When you send a a message with over 140 characters, you get [an error message from robin](http://i.imgur.com/KKWk1W8.png).

**Comment by vartan** [comment]
Good catch @wc1202 . One thing we could do is if it's over the limit, truncate it to the limit and put the rest in your text box. Don't have time to do any work myself right now

**Comment by IAP-Reloaded** [comment]
Take into account the rate limit.

**Comment by ghost** [comment]
If the rate limit is client-side, maybe it could be disabled or reduced?

**Comment by fz6** [comment]
It's server side, and it gets harsher the more users there are in the room.
