### ISSUE TITLE
Join multiple channels with one account?

### ISSUE THREAD

**Issue by ghost** [vartan/robin-grow#157]
Is this possible?

**Comment by vartan** [comment]
Separate by commas :) You will get tabs at the top

**Comment by ghost** [comment]
How do I do it?

**Comment by vartan** [comment]
Are you talking about entire chat rooms? Or channels.

**Comment by ghost** [comment]
I mean join a new entire chat room.

Like two sessions at once.

Is it possible with modifying cookies and what not?

**Comment by vartan** [comment]
Nah that's not gonna be possible. It's tied to your account on the server's end.

**Comment by thenoncoder** [comment]
:(

**Comment by ghost** [comment]
Maybe emulate a fake server connection?

**Comment by vartan** [comment]
It's tied to your account. Make a new incognito window and log in there with a new acct.

**Comment by ghost** [comment]
I'm already on one.

**Comment by vartan** [comment]
Download more browsers :)

**Comment by dkisselev** [comment]
https://chrome.google.com/webstore/detail/swap-my-cookies/dffhipnliikkblkhpjapbecpmoilcama?hl=en

(or whatever equivalent there is for your browser).

You still need a reddit account for each one, and will probably only be able to look at/use one account at a time, but other than this, your next best option is more browsers.

**Comment by vartan** [comment]
@dkisselev: Will it work when the page refreshes on a merge?

**Comment by dkisselev** [comment]
I haven't used cookie swappers in a while, but it just updates the browser cookie store and changes the cookie sets in the background.

So probably not, if you load the page with profile A, then change to PB; when the page changes, the browser will set PB cookies and you'll get back a refresh of PB.

It's essentially a faster way to switch accounts than logging out/in (not a way to keep two going at the same time). You might be able to make it work if you load a chat page, then switch profiles and load another chat page, but refreshes will kill it.
