### ISSUE TITLE
Trivia Bot?

### ISSUE THREAD

**Issue by ghost** [vartan/robin-grow#159]
I don't know who made the trivia bot, but is it possible to add some version of it directly in the script?

Like press a button to activate it and it automatically sends messages using your username?

**Comment by tetra-fox** [comment]
I personally think that this would be too much for the script. This script is more of a "Robin Enhancement Suite" (see what i did there? :grin:) It would (and should) be a seperate script. But this is up to @vartan.

**Comment by vartan** [comment]
Agreed.
