### ISSUE TITLE
how to run script

### ISSUE THREAD

**Issue by curioussavage** [vartan/robin-grow#19]
hey guys I'm out of the loop I think, how are people running this script? are the comments at the top for a format for a chrome extension?

I think I'm going to ditch my own extension since I can't work on it anymore

**Comment by pedro-mass** [comment]
...thru the browser console

**Comment by curioussavage** [comment]
well duh pedro. 

but there is a userscript comment at the top which clearly is used by some other thing probably a chrome extension.

just pasting it in the console is crappy since there is a page refresh on room change

**Comment by Qjammer** [comment]
You should download a script runner like greasemonkey or tampermonkey, then go here: https://github.com/vartan/robin-grow/raw/master/robin.user.js and install the script.

Another possibility, which involves less hassle but you'll have to update it every time you reopen the tab, is through the developer console

**Comment by MWin123** [comment]
Install guide: https://www.reddit.com/r/joinrobin/comments/4cwk2s/automatic_grow_userscript_bot/

**Comment by curioussavage** [comment]
thanks guys
