### ISSUE TITLE
The script doesn't work in firefox

### ISSUE THREAD

**Issue by Lainiel** [vartan/robin-grow#21]
It worked on the previous version 0.7 or 0.8 I think, now the greasemonkey recognizes that the script is loaded but it doesn't do anything.

**Comment by vartan** [comment]
Thanks for opening this issue. Have you tried uninstalling and reinstalling? One thing I had to do at some point was add permissions for GM_save and GM_get stuff.

If it still doesn't work, can you open the developer console and report any errors? Thank you!

**Comment by Lainiel** [comment]
I tried reinstalling both the script and greasemonkey and it didn't work.
The console throws some No element found errors, but they are there even when greasemonkey is disabled.

**Comment by vartan** [comment]
I think greasemonkey might have sanitized jquery out of the scope somehow. Try the newest version which should include jquery

**Comment by NetNerd** [comment]
not working for me still..... looks like something near 1.0 broke it (which is around where the 'GM_' stuff was added I think.....)

**Comment by vartan** [comment]
Sorry can you try one more time, I think i accidentally overwrote the change I made when merging something.

I tested it on my local copy of firefox. Make sure you are loading 1.51, when i tried to update it was trying to pull an old version.

**Comment by NetNerd** [comment]
yep. that's got it working. thanks
