### ISSUE TITLE
Toggle options

### ISSUE THREAD

**Issue by codyrobert** [vartan/robin-grow#28]
Not an issue, just a heads up: will be working on building options to toggle the spam filters / allow input of specific strings / users.

**Comment by TheElectroclassics** [comment]
Can you also create a toggle where only displays the votes?

**Comment by codyrobert** [comment]
as in you'd only want to see the vote text and no other messages?

**Comment by TheElectroclassics** [comment]
Yep

**Comment by PeachIceTea** [comment]
There was just a merge adding a settings menu. I hope it works properly.

**Comment by PeachIceTea** [comment]
Its broken ... Of course it is. Fixing it right now.

**Comment by codyrobert** [comment]
Thanks @PeachIceTea!
