### ISSUE TITLE
Will type `/vote grow` after filtering out old messages

### ISSUE THREAD

**Issue by vartan** [vartan/robin-grow#29]
it filters out the "you have already voted grow" message and then the script no longer knows not to vote.

**Comment by JimRaynor56** [comment]
I'm just getting [object Object] now in the text field.

**Comment by vartan** [comment]
oops i just fixed that i think

**Comment by JimRaynor56** [comment]
It no longer writes [object Object].  But it's not correctly replacing any text I had typed in the box.

**Comment by dashed** [comment]
@vartan doing js code live ;)

**Comment by JimRaynor56** [comment]
@vartan scratch that.  It's working after your most recent update.  Nice fix.

**Comment by vartan** [comment]
yeah ithink i might have fixed it now, trying to fix my bugs before people update it but im hitting other bugs..

I think the spam filter is filtering out the 'already voted' thing.

**Comment by dashed** [comment]
I'm getting `[object Object]`. :P

**Comment by JimRaynor56** [comment]
@dashed Github is still caching the bugged raw text.  I had to copy in manually.

**Comment by dashed** [comment]
@JimRaynor56 ah good catch. I used the raw ffrom this commit: https://github.com/vartan/robin-grow/blob/f49006d4c6bc18a19d377321f8f3b78c3948ace8/robin.user.js

**Comment by Bineary** [comment]
It seems like the script is no longer voting to grow (1.55).  I noticed it hadn't voted after the merge, refreshed to confirm.  Voted to stay and refreshed, my vote has not changed to grow.

**Comment by Bineary** [comment]
Ignore the above, seems to be fixed in a recent version, thanks!
