### ISSUE TITLE
[object Object] in Chat Box

### ISSUE THREAD

**Issue by xerohour** [vartan/robin-grow#32]
Constant [object Object] text in Chat Box Field

**Comment by vartan** [comment]
Please update, your browser might have cached the script so try refreshing the script and pasting the new code in. That issue was fixed a couple commits ago.

**Comment by dashed** [comment]
Go latest commit and click 'raw' to update/reinstall. Like this: https://github.com/vartan/robin-grow/blob/f691fab7fe9caefdcb25d1d1e793e05af5bb3471/robin.user.js
