### ISSUE TITLE
Handle reddit downtime

### ISSUE THREAD

**Issue by dkisselev** [vartan/robin-grow#33]
Other scripts look to be just configuring a page refresh on some interval. Otherwise a few seconds of reddit downtime take you away from the robin page, which leads to abondonment.

```
setTimeout(function(){
        window.location.reload();
    }, 300000);
```

is what I've seen others do, we might be able to come up with a more elegant solution

**Comment by vartan** [comment]
Right now we have this for refreshing

```
var lastChatString = $(".robin-message--timestamp").last().attr("datetime");
var timeSinceLastChat = new Date() - (new Date(lastChatString));
var now = new Date();
if(timeSinceLastChat !== undefined && (timeSinceLastChat > 60000 && now-timeStarted > 60000)) {
```

it seems like something like this might work, but i can't really test it

```
var timestampExists = $(".robin-message--timestamp") !== undefined;
var lastChatString = $(".robin-message--timestamp").last().attr("datetime");
var lastTime = (new Date(lastChatString));
var timeSinceLastChat = new Date() - lastTime;
var now = new Date();

if(timeSinceLastChat !== undefined && (timeSinceLastChat > 60000 && now-timeStarted > 60000)
    || (now-timeStarted > 10000 && !timeStampExists)) {
```

**Comment by dkisselev** [comment]
Yeah, that's the hard part, you can't really test it until robin attempts to push a refresh.

**Comment by vartan** [comment]
You can refresh yourself but you have to hit an error page

**Comment by dashed** [comment]
You can test using network tools in Chrome devtools: https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/network-conditions?hl=en

**Comment by vartan** [comment]
Need to simulate a server-side error

**Comment by vartan** [comment]
It's in the newest version if you can manage to get an error to test it

**Comment by dashed** [comment]
@vartan what am I supposed to look for?

**Comment by devoidfury** [comment]
This should be working in recent versions.
