### ISSUE TITLE
Version 1.59 only votes grow regardless of user choice

### ISSUE THREAD

**Issue by Valiant-Wolf** [vartan/robin-grow#46]
Voting behaviour in version 1.57 appeared to function correctly

**Comment by dashed** [comment]
haha. i noticed this...

**Comment by PeachIceTea** [comment]
Similar to #45 . We need to decide whether we want to support all options or not. It is called robin-GROW after all.

**Comment by dashed** [comment]
should be able to enable/disable grow...

**Comment by Icehawk78** [comment]
I'd actually prefer if it allowed you to select whether to stay/grow/not vote.

**Comment by PeachIceTea** [comment]
I am working on that Icehawk78

**Comment by PeachIceTea** [comment]
#54

**Comment by PeachIceTea** [comment]
Should be fixed with #54
