### ISSUE TITLE
Click-to-mute Users in Chat

### ISSUE THREAD

**Issue by Icehawk78** [vartan/robin-grow#50]
In larger groups, it's nearly impossible to find anyone in the userlist, both because it seems to limit it to 200 displayed users, and because it's not sorted in any manner.

It would be more useful to be able to click on a message and extract the user from that and mute them that way. Not certain how you'd handle unmuting in that manner, in case you muted the wrong person, though.

**Comment by PeachIceTea** [comment]
Well we could generate a list in the settings menu with all muted users. So that shouldn't be a problem.

**Comment by dashed** [comment]
~~or a whitelist of configurable prefixes on messages...~~

**Comment by Icehawk78** [comment]
@dashed - That's not really related to muting functionality

**Comment by dashed** [comment]
@Icehawk78 yeah you're right. :+1:

**Comment by Icehawk78** [comment]
It looks like when this functionality was added, the on-message spam filter was removed.

**Comment by devoidfury** [comment]
This was added and is working.
