### ISSUE TITLE
Auto clear old messages

### ISSUE THREAD

**Issue by dashed** [vartan/robin-grow#53]

**Comment by PeachIceTea** [comment]
I think I already saw code for that. Might have been removed tho. Let me see.

**Comment by Shou** [comment]
Yeah it's already in there. I also made it more efficient in #25 https://github.com/vartan/robin-grow/pull/25/commits/53527772c6c580b907f24c093dd7c378d10dc861

**Comment by PeachIceTea** [comment]
It seems like it got removed.

**Comment by Shou** [comment]
@PeachIceTea It's originally hiding inside `findAndHideSpam` here, https://github.com/vartan/robin-grow/blob/master/robin.user.js#L129

**Comment by PeachIceTea** [comment]
Ah. I'm blind ... Maybe we should set it lower. My tab is crashing quite often.

**Comment by dkisselev** [comment]
Mine's also crashing, lower might help

**Comment by Shou** [comment]
I doubt it's the amount of messages that's problematic itself, but some of the code inefficiently goes over every message when it isn't necessary. I'm thinking of a way to make `findAndHideSpam` work with MutationObservers.

**Comment by PeachIceTea** [comment]
So it is the amount of messages. Setting it to 250 makes the problem disappear. Although that is a little low.

**Comment by kcstllo** [comment]
I changed it from 1000 to 250 and I'm not having any problems so far. I wasn't really having any problems beforehand, however I did notice small lag. Therefore, lowering this may help others.

**Comment by dkisselev** [comment]
yeah, mine's at 300 and feels good, will keep you guys posted about long-term results (if you don't hear from me, things are probably working well)

**Comment by Shou** [comment]
@PeachIceTea Right now yes, what I'm trying to say is you can have both 1,000 messages and not a slow browser.

**Comment by PeachIceTea** [comment]
@Shou I got it. Sorry for being so nit picky ;) I will add a way to set the amount via the settings menu when I wake up tomorrow. Good night :)

**Comment by Shou** [comment]
Sleep tight pupper

Also sweet, I'll try to make it more accommodating to that change.

**Comment by vartan** [comment]
I can go put it at 250, I picked 1000 arbitrarily before the spam filtering was good.

**Comment by vartan** [comment]
you nkow what yeah, it got disappeared at some point in merging

**Comment by vartan** [comment]
I am in a tiny chat, could someone verify this works correctly now? At one point i had it pruning 1000 messages, someone got rid of it and i didn't notice

**Comment by dashed** [comment]
Unsure... but the botspam isn't removed anymore..

**Comment by dashed** [comment]
This works. But the merge somehow broke it; I've fixed it as part of this PR: https://github.com/vartan/robin-grow/pull/63

**Comment by devoidfury** [comment]
This is working now.
