### ISSUE TITLE
Stop user from posting while rate limiting is in effect

### ISSUE THREAD

**Issue by matchai** [vartan/robin-grow#66]
Instead of having the user's post being declined after it has been posted, an indicator could appear when a user's post can be sent.
This would avoid any aggravation from having to retype the text, since it has been removed from the text input.

This could either be done as a count-down, a visual indicator to show that you can now post, or simply stopping the user's post from being sent until rate limiting has ended.

**Comment by devoidfury** [comment]
robin-grow catches this and saves your message in the box so you can resubmit again later.
