### ISSUE TITLE
Time left is always stuck at 0 (Chrome)

### ISSUE THREAD

**Issue by Oqwert** [vartan/robin-grow#69]
http://puu.sh/o37QE/76cadf06b5.png

**Comment by PeachIceTea** [comment]
Hm, thats weird I use chrome and everything is working fine here. Could you try [this](https://github.com/PeachIceTea/robin-grow/raw/patch%231/robin.user.js) version of the script and report back?

**Comment by relative2** [comment]
This is happening to me too.

**Comment by dkisselev** [comment]
When you're in a big room that's waiting to merge, robin will say "voting will end soon", so the timer actually is at 0.

In big rooms it takes a long time for another room to get big enough to merge, so you wait in limbo until that time. The system checks for compatible rooms every minute though.

**Comment by hplewis** [comment]
Refresh and check the time left that Robin states. If it says that voting is ending soon, that is likely why. As dkisselev said, it will stay this way until you are able to merge.

**Comment by Oqwert** [comment]
Refreshing doesn't help, and it also happens on rooms that have just merged so there's no way the time is actually 0.

**Comment by Oqwert** [comment]
Refreshing doesn't help, and it also happens on rooms that have just merged so there's no way the time is actually 0. The version PeachIceTea linked fixed the problem.

**Comment by hplewis** [comment]
If so, then you can close this issue.
