### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by africabound** [vartan/robin-grow#80]
Can you just add a checkbox to each name and allow us to choose who to mute?

**Comment by daegalus** [comment]
you can click on anyone in the chatroom, or on the userlist and it will mute them

**Comment by africabound** [comment]
Thanks for the info

**Comment by vartan** [comment]
@Daegalus, the thing is, it doesn't show everyones name on the right side.

The only solution is to take the actual list of users and redo the user list using that.

**Comment by daegalus** [comment]
Oh I know, I was just offering something. Userlist is limited, but in the chat itself it has everyone as they spam, so its easier to snipe them.
