### ISSUE TITLE
List of Muted Peopled to unmute

### ISSUE THREAD

**Issue by hplewis** [vartan/robin-grow#84]
It would be beneficial to provide a list of people who are currently muted (possibly through the settings menu) who you can then unmute. It seems there is no way to unmute people currently.

**Comment by vartan** [comment]
Does refreshing work?

**Comment by hplewis** [comment]
Yes. Refreshing unmutes everyone muted.

**Comment by hplewis** [comment]
This has been implemented in a recent patch.
