### ISSUE TITLE
From 1.661 to 1.7 is a downgrade (according to Tampermonkey).

### ISSUE THREAD

**Issue by SysadminJeroen** [vartan/robin-grow#93]
I believe that the only way to fix this is to use 2.0.0 next time.

**Comment by vartan** [comment]
lol... thank you for letting me know not to do this anymore

**Comment by vartan** [comment]
Using 1.700, I think this will fix it?

**Comment by SysadminJeroen** [comment]
I believe so.

**Comment by SysadminJeroen** [comment]
I am not 100% sure, but it makes sense that it would fix the issue.

**Comment by SysadminJeroen** [comment]
If you're going to change the next patch to 1.700, you mad man, be sure to set your Tampermonkey revision to 1.661 to test it.
I probably can't help you because I'm going to snooze right now.

**Comment by dkisselev** [comment]
It just uses numbers in chronological order, 611 > 7 so it seems like a downgrade.

You're right that 700 would work though, 700 > 611.
