### ISSUE TITLE
Script stops?

### ISSUE THREAD

**Issue by meganukebmp** [vartan/robin-grow#98]
For some reason the script auto stops after some time.
Mentions stop working and spam appears.

**Comment by vartan** [comment]
What version are you on?

**Comment by meganukebmp** [comment]
1.702

Console log
reddit-init.en.4zDJW8DVG30.js:5 Client Error: "ReferenceError: messages is not defined" thrown at L295:36 in https://www.reddit.com/robin Message: "Uncaught ReferenceError: messages is not defined" Object {tag: "unknown"}r.logging.sendError @ reddit-init.en.4zDJW8DVG30.js:5r.logging.sendException @ reddit-init.en.4zDJW8DVG30.js:5e.onerror @ reddit-init.en.4zDJW8DVG30.js:5
reddit-init.en.4zDJW8DVG30.js:5 Not sending debug log; already sent 3

**Comment by vartan** [comment]
I fixed that one a while ago
